
--1 DANH SÁCH SẢN PHẨM CÓ MÃ PHIẾU YC9912
SELECT TENSP
FROM SANPHAM,CHITIETHD
WHERE MAHD LIKE 'YC9912' AND MA_SP=MASP
--2 TỔNG THÀNH TIỀN 3 THÁNG CUỐI NĂM
SELECT SUM(TONGGIA) TONGTHANHTIEN2017
FROM HOADON
WHERE YEAR(NGAYLAPHD) = 2017 AND NGAYLAPHD BETWEEN '2017/10/01' AND '2017/12/31'
--5 TOP 3 SẢN PHẢM NHẬP NHIỀU NHẤT 2017
SELECT TOP 3(SLNHAP),TENSP
FROM SANPHAM
WHERE YEAR(NGNHAPHANG)=2017
ORDER BY SLNHAP DESC
--4 TOP 3 SẢN PHẨM BÁN CHẠY NHẤT 2017
SELECT TOP 3 SP.TENSP,MASP,SUM(CT.SOLUONG) SL
FROM SANPHAM SP,CHITIETHD CT
WHERE YEAR(NGAYLAPHD)=2017 AND MA_SP = MASP
GROUP BY MASP,TENSP
ORDER BY SL DESC
--3 TÊN CÁC SẢN PHẨM CÓ KHUYẾN MÃI 10%
SELECT TENSP
FROM KHUYENMAI,SANPHAM
WHERE UUDAI = 0.1 AND MA_KM=MAKM